/**
 * 常量键值对
 */
import Api from 'api/api'
const USER_INFO='USER_INFO';
const SESSIONSTORAGE="sessionStorage";
const LOCALSTORAGE="localStorage";
const BASE_URL=Api.BASE_URL;
const KEEP="KEEP";//快捷导航
const BREADCRUMB="BREADCRUMB";
const ACTIVE_MENU="ACTIVE_MENU";
const ACTIVE_NAV='ACTIVE_NAV'
export {USER_INFO,SESSIONSTORAGE,LOCALSTORAGE,BASE_URL,KEEP,BREADCRUMB,ACTIVE_MENU,ACTIVE_NAV}

